---
- name: Create Troshka secrets
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: troshka-secrets
        namespace: "{{ troshka_namespace }}"
      type: Opaque
      stringData:
        jwt-secret: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=43') }}"
        encryption-key: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=43') }}"
        database-url: "postgresql+psycopg2://troshka:{{ _postgres_password }}@troshka-postgres:5432/troshka"
        s3-access-key: "{{ _s4_access_key }}"
        s3-secret-key: "{{ _s4_secret_key }}"
